config/routes.rb
Rails.application.routes.draw do

  resources :tasks do
    member do
      patch 'mark_as_done'
      patch 'mark_as_open'
    end
  end

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :sessions

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :user

  STATUSES = {
    done: "Done",
    open: "Open",
  }

  validates :name, :user_id, presence: true
  before_save :set_defaults

  # owner scopes
  scope :by_user, -> (user_id) { where(user_id: user_id) }

  # status scopes
  scope :open, -> { by_status(STATUSES[:open]) }
  scope :done, -> { by_status(STATUSES[:done]) }
  scope :by_status, -> (status) { where(status: status) }

  # due date scopes
  scope :past, -> { where("due_date < ?", Date.today) }
  scope :due_today, -> { where("due_date = ?", Date.today) }
  scope :future, -> { where("due_date > ?", Date.today) }

  # sort scopes
  scope :sorted, -> { order(:due_date) }

  private

  def set_defaults
    self.status ||= "Open"
    self.due_date ||= Date.today
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_many :tasks, dependent: :destroy
	validates_uniqueness_of :email
	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user 
	def current_user 
	  @current_user ||= User.find(session[:user_id]) if session[:user_id] 
	end

  def require_user
    redirect_to '/login' unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password_digest])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      flash[:errors] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy 
    session[:user_id] = nil 
    redirect_to '/' 
  end
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :require_user

  def index
    @past_due_tasks  = current_user.tasks.open.past.sorted.to_a
    @today_tasks     = current_user.tasks.due_today.open.sorted.to_a
    @future_tasks    = current_user.tasks.future.open.sorted.to_a
    @completed_tasks = current_user.tasks.done.sorted.to_a
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.create(task_params.merge(user_id: current_user.id))
    if task.errors.present?
      flash[:errors] = task.errors.full_messages
    end  
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(task_params)
    redirect_to tasks_path
  end

  def mark_as_done
    @task = Task.find(params[:id])
    @task.update_attributes(status: "Done")
    redirect_to tasks_path
  end

  def mark_as_open
    @task = Task.find(params[:id])
    @task.update_attributes(status: "Open")
    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :due_date, :status)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create 
  @user = User.create(user_params) 
    if @user.errors.present?
      flash[:errors] = @user.errors.full_messages
      redirect_to signup_path
    else
      session[:user_id] = @user.id
      redirect_to tasks_path
    end
  end

private
  def user_params
    params.require(:user).permit(:email, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scheduler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<div class="navbar">
  <% if current_user %> 
    <ul class="nav nav-tabs pull-left"> 
      <!--<li><%= current_user.email %></li> -->
      <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
    </ul> 
  <% else %> 
    <ul class="nav nav-tabs pull-left"> 
      <li><%= link_to "Login", 'login' %></a></li> 
      <li><%= link_to "Signup", 'signup' %></a></li> 
    </ul> 
  <% end %>
</div>

<body>

<% if flash[:errors].present? %>
  </br>
  <div class="alert alert-danger" role="alert" id="errors"><%= Array(flash[:errors]).join("<br/>").html_safe %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
  </br>
  <%= form_for :task, html: {class: 'form-inline'}, :url => { :action => 'create' } do |f| %>
  <div class="form-group">
    <%= f.text_field :name, :class => "form-control input-lg", :placeholder => "New todo"%>
  </div> &emsp;
  <div class="form-group">
    <%= f.date_field :due_date, :class => "form-control input-lg", :value => Date.today %>
  </div> &emsp;
  <div class="input-group">
  <%= f.submit class: 'btn btn-success btn-lg' %>
  </div>
  <% end %>

 

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

  </br>
  <%= form_for :task, html: {class: 'form-inline'}, :method => 'patch', :url => { :action => 'update' } do |f| %>
  <div class="form-group">
    <%= f.text_field :name, :class => "form-control input-lg", :placeholder => "New todo"%>
  </div> &emsp;
  <div class="form-group">
    <%= f.date_field :due_date, :class => "form-control input-lg" %>
  </div> &emsp;
  <div class="input-group">
  <%= f.submit class: 'btn btn-success btn-lg' %>
  </div>
  <% end %>

app/views/tasks/index.html.erb
<!DOCTYPE html>
<html lang="en">

<h1>To-Do List</h1>

<%= render "form" %>

</br>

<ul class="list-group">
    <h4> Past-due items </h4>
  <% if @past_due_tasks.empty? %>
    <li class="list-group-item"> You don't have any past-due items. </li>
  <% end %>
  <% @past_due_tasks.each do |task| %>
    <li class="list-group-item"> <%= link_to '<span class="glyphicon glyphicon-check"></span>'.html_safe, mark_as_done_task_path(task),title: 'Mark as done', 'data-toggle' => 'tooltip','data-placement' => 'bottom', method: :patch, class: 'btn btn-success btn-sm'%> <%= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe, edit_task_path(task), title: 'Edit', 'data-toggle' => 'tooltip','data-placement' => 'bottom', class: 'btn btn-info btn-sm' %> <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, task_path(task), title: 'Delete', 'data-toggle' => 'tooltip','data-placement' => 'bottom', method: :delete, data: { confirm: 'Are you sure you want to delete this task?' }, class: 'btn btn-danger btn-sm' %>&emsp;<%= task.name%></li>
  <% end %>
</ul>

<ul class="list-group">
    <h4> Today's to-do list </h4>
  <% if @today_tasks.empty? %>
    <li class="list-group-item"> Nothing on your to-do list for today! </li>
  <% end %>
  <% @today_tasks.each do |task| %>
    <li class="list-group-item"> <%= link_to '<span class="glyphicon glyphicon-check"></span>'.html_safe, mark_as_done_task_path(task),title: 'Mark as done', 'data-toggle' => 'tooltip','data-placement' => 'bottom', method: :patch, class: 'btn btn-success btn-sm' %> <%= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe, edit_task_path(task),title: 'Edit', 'data-toggle' => 'tooltip','data-placement' => 'bottom', class: 'btn btn-info btn-sm' %> <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, task_path(task),title: 'Delete', 'data-toggle' => 'tooltip','data-placement' => 'bottom', method: :delete, data: { confirm: 'Are you sure you want to delete this task?' }, class: 'btn btn-danger btn-sm' %>&emsp;<%= task.name%> </li>
  <% end %>
</ul>

<div class="panel-group">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapse1">Due later</a>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse">
      <ul class="list-group">
          <!--<h4> Due tomorrow and later </h4> -->
        <% if @future_tasks.empty? %>
          <li class="list-group-item"> Nothing on your to-do list for later. </li>
        <% end %>
        <% @future_tasks.each do |task| %>
          <li class="list-group-item"> <%= link_to '<span class="glyphicon glyphicon-check"></span>'.html_safe, mark_as_done_task_path(task), title: 'Mark as done', 'data-toggle' => 'tooltip','data-placement' => 'bottom',method: :patch, class: 'btn btn-success btn-sm' %> <%= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe, edit_task_path(task),title: 'Edit', 'data-toggle' => 'tooltip','data-placement' => 'bottom', class: 'btn btn-info btn-sm' %> <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, task_path(task),title: 'Delete', 'data-toggle' => 'tooltip','data-placement' => 'bottom', method: :delete, data: { confirm: 'Are you sure you want to delete this task?' }, class: 'btn btn-danger btn-sm' %>&emsp; <%= task.due_date.to_formatted_s(:long) %>  - <%= task.name %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="panel-group">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapse2">Done</a>
      </h4>
    </div>
    <div id="collapse2" class="panel-collapse collapse">
      <ul class="list-group">
          <!-- <h4> Completed tasks </h4> -->
        <% if @completed_tasks.empty? %>
          <li class="list-group-item"> You don't have any completed tasks. </li>
        <% end %>
        <% @completed_tasks.each do |task| %>
          <li class="list-group-item"> <%= link_to '<span class="glyphicon glyphicon-minus"></span>'.html_safe, mark_as_open_task_path(task),title: 'Mark as open', 'data-toggle' => 'tooltip','data-placement' => 'bottom', method: :patch, class: 'btn btn-warning btn-sm' %> <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, task_path(task),title: 'Delete', 'data-toggle' => 'tooltip','data-placement' => 'bottom', method: :delete, data: { confirm: 'Are you sure you want to delete this task?' }, class: 'btn btn-danger btn-sm' %>&emsp;<%= task.name%></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

</html>

app/views/tasks/new.html.erb
<h1>Add a task</h1>

<%= render "form" %>

app/views/users/new.html.erb
</br>

<%= form_for :user, html: {class: 'form-inline'}, :url => { :action => 'create' } do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, :class => "form-control input-lg"%>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => "form-control input-lg"%>
    &emsp;
  <div class="input-group">
    <%= f.submit :value => "Sign-up!", class: 'btn btn-success btn-lg' %>
  </div>
<% end %>

 